import {
	LayoutDashboard,
	Sparkles,
	FileText,
	ImagePlus,
	VideoIcon,
	AudioLines,
	FileSearch,
	PenLine,
	PenSquare,
	CalendarDays,
	ListTodo,
	Layers,
	Clock,
	Inbox,
	MessagesSquare,
	Tag,
	Users,
	BarChart3,
	FileBarChart,
	FileSpreadsheet,
	CalendarCheck,
	Megaphone,
	Folders,
	Image,
	Target,
	Plug,
	Bot,
	Link2,
	Palette,
	Building2,
	Briefcase,
	Globe,
	Shield,
	Receipt,
	ClipboardList,
	Settings,
	Activity,
	CreditCard,
	MessageSquare,
	LayoutGrid,
	Presentation,
	Database,
	FileAudio,
	Film,
	Clapperboard,
	CircleDollarSign,
	TrendingUp,
	ShoppingCart,
	SquareStack,
	FileImage,
	ScrollText,
	History,
	Headphones,
	FolderOpen,
	FileCode2,
	Wallet,
	PieChart,
	BookOpen,
	FileQuestion,
	LifeBuoy,
	Bug,
	Brain,
	Wrench,
	type LucideIcon,
} from "lucide-react";

export interface NavItem {
	label: string;
	path: string;
	icon: LucideIcon;
}

export interface NavGroup {
	label: string;
	icon?: LucideIcon;
	path?: string;
	items: NavItem[];
}

export const NAV_GROUPS: NavGroup[] = [
	{
		label: "",
		items: [
			{ label: "Dashboard", path: "/my", icon: LayoutDashboard },
			{ label: "CRM", path: "/my/crm", icon: Briefcase },
		],
	},
	{
		label: "CREATE",
		icon: Sparkles,
		path: "/my/captain",
		items: [
			{ label: "AI Captain", path: "/my/captain", icon: Sparkles },
			{ label: "Assistant", path: "/my/chat", icon: MessageSquare },
			{ label: "Captain Boards", path: "/my/ai-captain/boards", icon: LayoutGrid },
			{ label: "Templates", path: "/my/templates", icon: FileText },
			{ label: "Campaigns", path: "/my/campaigns", icon: Folders },
			{ label: "Image Generator", path: "/my/image-generator", icon: ImagePlus },
			{ label: "Video Generator", path: "/my/text-to-video", icon: VideoIcon },
			{ label: "Image to Video", path: "/my/image-to-video", icon: Film },
			{ label: "Video Editor", path: "/my/video-editor", icon: Clapperboard },
			{ label: "Text to Audio", path: "/my/text-to-audio", icon: AudioLines },
			{ label: "Transcription", path: "/my/audio-to-text", icon: FileAudio },
			{ label: "Presentations", path: "/my/presentations", icon: Presentation },
			{ label: "Data Analyst", path: "/my/analyst", icon: Database },
			{ label: "Content Rewriter", path: "/my/content-rewriter", icon: PenLine },
			{ label: "Article Generator", path: "/my/article-generator", icon: FileSearch },
			{ label: "Editor", path: "/my/editor", icon: PenSquare },
		],
	},
	{
		label: "PUBLISH",
		icon: PenSquare,
		path: "/my/social-media/create-post",
		items: [
			{ label: "Create Post", path: "/my/social-media/create-post", icon: PenSquare },
			{ label: "Content Calendar", path: "/my/social-media/calendar", icon: CalendarDays },
			{ label: "Manage Posts", path: "/my/social-media/posts", icon: ListTodo },
			{ label: "Post Queues", path: "/my/social-media/queues", icon: Layers },
			{ label: "Bulk Scheduler", path: "/my/bulk-scheduler", icon: Clock },
			{ label: "Inbox", path: "/my/social-media/inbox", icon: Inbox },
			{ label: "Comments", path: "/my/social-media/comments", icon: MessagesSquare },
			{ label: "Labels", path: "/my/social-media/labels", icon: Tag },
			{ label: "Social Accounts", path: "/my/social-media/accounts", icon: Users },
		],
	},
	{
		label: "ANALYZE",
		icon: BarChart3,
		path: "/my/social-media/analytics",
		items: [
			{ label: "Analytics", path: "/my/social-media/analytics", icon: BarChart3 },
			{ label: "Reports", path: "/my/social-media/report", icon: FileBarChart },
			{ label: "Custom Reports", path: "/my/social-media/custom-report", icon: FileSpreadsheet },
			{ label: "Scheduled Reports", path: "/my/social-media/schedule-report", icon: CalendarCheck },
			{ label: "Facebook Ads", path: "/my/integrations/facebook/ads", icon: CircleDollarSign },
			{ label: "Google Ads", path: "/my/integrations/google/ads", icon: CircleDollarSign },
			{ label: "TikTok Ads", path: "/my/integrations/tiktok/ads", icon: CircleDollarSign },
			{ label: "LinkedIn Ads", path: "/my/integrations/linkedin/ads", icon: CircleDollarSign },
			{ label: "Google Analytics", path: "/my/integrations/google/traffic", icon: TrendingUp },
			{ label: "WooCommerce", path: "/my/integrations/woocommerce/insights", icon: ShoppingCart },
		],
	},
	{
		label: "AD MANAGER",
		icon: Megaphone,
		path: "/my/ad-manager",
		items: [
			{ label: "Dashboard", path: "/my/ad-manager", icon: Megaphone },
			{ label: "Campaigns", path: "/my/ad-manager/campaigns", icon: Folders },
			{ label: "Ad Sets", path: "/my/ad-manager/ad-sets", icon: SquareStack },
			{ label: "Ads", path: "/my/ad-manager/ads", icon: FileImage },
			{ label: "Creatives", path: "/my/ad-manager/creatives", icon: Image },
			{ label: "Audiences", path: "/my/ad-manager/audiences", icon: Target },
			{ label: "Analytics", path: "/my/ad-manager/analytics", icon: BarChart3 },
			{ label: "Audit Log", path: "/my/ad-manager/audit-log", icon: ScrollText },
			{ label: "Settings", path: "/my/ad-manager/settings", icon: Settings },
		],
	},
	{
		label: "CRM",
		icon: Briefcase,
		path: "/my/crm",
		items: [
			{ label: "Dashboard", path: "/my/crm", icon: LayoutDashboard },
			{ label: "Pipeline", path: "/my/crm/pipeline", icon: LayoutGrid },
			{ label: "Projects", path: "/my/crm/projects", icon: FolderOpen },
			{ label: "Contacts", path: "/my/crm/contacts", icon: Users },
			{ label: "Tasks", path: "/my/crm/tasks", icon: ClipboardList },
		],
	},
	{
		label: "CONNECT",
		icon: Plug,
		path: "/my/integrations",
		items: [
			{ label: "Integrations", path: "/my/integrations", icon: Plug },
			{ label: "URL Shortener", path: "/my/url-shortener", icon: Link2 },
			{ label: "Canva", path: "/my/canva", icon: Palette },
		],
	},
	{
		label: "AUTOMATE",
		icon: Bot,
		path: "/my/chatbot",
		items: [
			{ label: "Chatbot", path: "/my/chatbot", icon: Bot },
			{ label: "Templates", path: "/my/chatbot/templates", icon: FileText },
			{ label: "Analytics", path: "/my/chatbot/analytics", icon: BarChart3 },
			{ label: "Chat History", path: "/my/chatbot/history", icon: History },
			{ label: "Live Agent", path: "/my/chatbot/live-agent", icon: Headphones },
			{ label: "Settings", path: "/my/chatbot/settings", icon: Settings },
		],
	},
	{
		label: "WORKSPACE",
		icon: Building2,
		path: "/my/workspace",
		items: [
			{ label: "Overview", path: "/my/workspace", icon: Building2 },
			{ label: "Members", path: "/my/workspace?tab=Members", icon: Users },
			{ label: "Brands", path: "/my/brands", icon: Briefcase },
			{ label: "Business Groups", path: "/my/businesses", icon: Building2 },
			{ label: "Media Library", path: "/my/media", icon: FolderOpen },
			{ label: "Documents", path: "/my/documents", icon: FileText },
			{ label: "Developer API", path: "/my/developer", icon: FileCode2 },
			{ label: "Billing", path: "/my/billing", icon: Wallet },
		],
	},
	{
		label: "WHITELABEL",
		icon: Globe,
		path: "/my/whitelabel",
		items: [
			{ label: "Settings", path: "/my/whitelabel", icon: Globe },
			{ label: "Agency", path: "/my/agency", icon: Building2 },
			{ label: "Billing", path: "/my/agency/billing", icon: CreditCard },
			{ label: "Reports", path: "/my/agency/reports", icon: PieChart },
		],
	},
];

export const ADMIN_GROUP: NavGroup = {
	label: "ADMIN",
	icon: Shield,
	path: "/admin",
	items: [
		{ label: "Dashboard", path: "/admin", icon: Shield },
		{ label: "Users", path: "/admin/users", icon: Users },
		{ label: "Plans", path: "/admin/plans", icon: CreditCard },
		{ label: "Pricing", path: "/admin/pricing", icon: CircleDollarSign },
		{ label: "Subscriptions", path: "/admin/subscriptions", icon: ClipboardList },
		{ label: "Transactions", path: "/admin/transactions", icon: Receipt },
		{ label: "Templates", path: "/admin/templates", icon: FileText },
		{ label: "Assistants", path: "/admin/assistants", icon: Bot },
		{ label: "Blogs", path: "/admin/blogs", icon: BookOpen },
		{ label: "Pages", path: "/admin/pages", icon: FileQuestion },
		{ label: "Reports", path: "/admin/reports", icon: FileBarChart },
		{ label: "Support", path: "/admin/support", icon: LifeBuoy },
		{ label: "AI Captain Traces", path: "/admin/ai-captain/traces", icon: Activity },
		{ label: "AI Captain KB", path: "/admin/ai-captain/kb", icon: Brain },
		{ label: "AI Captain Skills", path: "/admin/ai-captain/skills", icon: Wrench },
		{ label: "Billing Debug", path: "/admin/billing-debug", icon: Bug },
		{ label: "Whitelabel", path: "/admin/whitelabel", icon: Globe },
		{ label: "Settings", path: "/admin/settings", icon: Settings },
		{ label: "Monitoring", path: "/admin/monitoring", icon: Activity },
	],
};
