import { useState } from "react";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Sparkles } from "lucide-react";

/* ── AI Text Generation ─────────────────────────────────────────── */

interface AiTextProps { open: boolean; onClose: () => void; onUse: (text: string) => void }

export function AiTextModal({ open, onClose, onUse }: AiTextProps) {
	const [topic, setTopic] = useState("");
	const [contentType, setContentType] = useState("Social Media Post");
	const [tone, setTone] = useState("Professional");
	const [platform, setPlatform] = useState("facebook");
	const [generated, setGenerated] = useState("");
	const [loading, setLoading] = useState(false);

	function handleGenerate() {
		setLoading(true);
		// TODO: Wire to AI Captain API for real generation
		setTimeout(() => {
			setGenerated(`Here's a ${tone.toLowerCase()} ${contentType.toLowerCase()} about "${topic}" for ${platform}. This will be generated by AI Captain when connected.`);
			setLoading(false);
		}, 1500);
	}

	return (
		<Dialog open={open} onOpenChange={onClose}>
			<DialogContent className="max-w-lg">
				<DialogHeader><DialogTitle>AI Text Generation</DialogTitle></DialogHeader>
				<div className="space-y-4">
					<ModelBadge label="SmartlyQ AI" sub="Powered by AI Captain" gradient="from-blue-500 to-indigo-600" />
					<div>
						<Label>Content Type</Label>
						<Select value={contentType} onValueChange={setContentType}>
							<SelectTrigger className="text-sm"><SelectValue /></SelectTrigger>
							<SelectContent>
								{["Social Media Post", "Blog Post", "Ad Copy", "Product Description", "Email Newsletter"].map((t) => <SelectItem key={t} value={t}>{t}</SelectItem>)}
							</SelectContent>
						</Select>
					</div>
					<div><Label>Topic / Context</Label><Textarea value={topic} onChange={(e) => setTopic(e.target.value)} placeholder="What should the post be about?" className="min-h-[80px] text-sm" /></div>
					<div className="grid grid-cols-2 gap-3">
						<div>
							<Label>Tone</Label>
							<Select value={tone} onValueChange={setTone}>
								<SelectTrigger className="text-sm"><SelectValue /></SelectTrigger>
								<SelectContent>
									{["Professional", "Casual", "Humorous", "Inspirational", "Formal", "Persuasive"].map((t) => <SelectItem key={t} value={t}>{t}</SelectItem>)}
								</SelectContent>
							</Select>
						</div>
						<div>
							<Label>Platform</Label>
							<Select value={platform} onValueChange={setPlatform}>
								<SelectTrigger className="text-sm"><SelectValue /></SelectTrigger>
								<SelectContent>
									{["facebook", "instagram", "twitter", "linkedin", "tiktok"].map((p) => <SelectItem key={p} value={p}>{p.charAt(0).toUpperCase() + p.slice(1)}</SelectItem>)}
								</SelectContent>
							</Select>
						</div>
					</div>
					{generated && (
						<div className="rounded-lg bg-[var(--muted)]/40 p-3"><p className="text-sm whitespace-pre-wrap">{generated}</p></div>
					)}
				</div>
				<DialogFooter className="border-t pt-4 flex gap-2">
					<Button variant="outline" onClick={onClose}>Cancel</Button>
					<Button onClick={handleGenerate} disabled={!topic || loading} className="bg-gradient-to-r from-blue-500 to-indigo-600 text-white gap-1.5">
						<Sparkles size={14} /> {loading ? "Generating..." : "Generate"}
					</Button>
					{generated && <Button variant="secondary" onClick={() => { onUse(generated); onClose(); setGenerated(""); setTopic(""); }}>Use This Content</Button>}
				</DialogFooter>
			</DialogContent>
		</Dialog>
	);
}

/* ── AI Image Generation ────────────────────────────────────────── */

interface AiImageProps { open: boolean; onClose: () => void; onUse: () => void }

export function AiImageModal({ open, onClose, onUse }: AiImageProps) {
	const [prompt, setPrompt] = useState("");
	const [preview, setPreview] = useState("");

	return (
		<Dialog open={open} onOpenChange={onClose}>
			<DialogContent className="max-w-lg">
				<DialogHeader><DialogTitle>AI Image Generation</DialogTitle></DialogHeader>
				<div className="space-y-4">
					<ModelBadge label="SmartlyQ AI — Image" sub="Generated images saved to Media Library." gradient="from-violet-500 to-indigo-600" />
					<div><Label>Prompt</Label><Textarea value={prompt} onChange={(e) => setPrompt(e.target.value)} placeholder="Describe the image you want..." className="min-h-[100px] text-sm" /></div>
					<div className="rounded-lg bg-[var(--muted)]/40 p-3 min-h-[60px]">
						<p className="text-sm text-[var(--muted-foreground)]">{preview || 'Click "Generate Image" to create an image.'}</p>
					</div>
				</div>
				<DialogFooter className="border-t pt-4 flex gap-2">
					<Button variant="outline" onClick={onClose}>Cancel</Button>
					<Button className="bg-gradient-to-r from-amber-400 to-orange-400 text-white gap-1.5" onClick={() => setPreview("🖼️ AI image will appear here once connected.")}>
						<Sparkles size={14} /> Generate Image
					</Button>
					<Button variant="secondary" disabled={!preview} onClick={() => { onUse(); onClose(); setPreview(""); setPrompt(""); }}>Use This Image</Button>
				</DialogFooter>
			</DialogContent>
		</Dialog>
	);
}

/* ── AI Video Generation ────────────────────────────────────────── */

interface AiVideoProps { open: boolean; onClose: () => void; onUse?: () => void }

export function AiVideoModal({ open, onClose }: AiVideoProps) {
	const [prompt, setPrompt] = useState("");
	const [type, setType] = useState("Text to Video");
	const [length, setLength] = useState("5s");
	const [resolution, setResolution] = useState("720p");

	return (
		<Dialog open={open} onOpenChange={onClose}>
			<DialogContent className="max-w-lg">
				<DialogHeader><DialogTitle>AI Video Generation</DialogTitle></DialogHeader>
				<div className="space-y-4">
					<div className="grid grid-cols-2 gap-3">
						<div><Label>Type</Label>
							<Select value={type} onValueChange={setType}><SelectTrigger className="text-sm"><SelectValue /></SelectTrigger>
								<SelectContent><SelectItem value="Text to Video">Text to Video</SelectItem><SelectItem value="Image to Video">Image to Video</SelectItem></SelectContent></Select>
						</div>
						<div><ModelBadge label="SmartlyQ AI — Video" sub="Saved to Media Library." gradient="from-teal-400 to-cyan-600" /></div>
					</div>
					<div className="grid grid-cols-3 gap-3">
						<div><Label>Length</Label>
							<Select value={length} onValueChange={setLength}><SelectTrigger className="text-sm"><SelectValue /></SelectTrigger>
								<SelectContent><SelectItem value="5s">5 seconds</SelectItem><SelectItem value="10s">10 seconds</SelectItem></SelectContent></Select>
						</div>
						<div><Label>Resolution</Label>
							<Select value={resolution} onValueChange={setResolution}><SelectTrigger className="text-sm"><SelectValue /></SelectTrigger>
								<SelectContent><SelectItem value="480p">480p</SelectItem><SelectItem value="720p">720p</SelectItem><SelectItem value="1080p">1080p</SelectItem></SelectContent></Select>
						</div>
						<div><Label>Quality</Label><Input value="Auto" disabled className="text-sm" /></div>
					</div>
					<div><Label>Prompt</Label><Textarea value={prompt} onChange={(e) => setPrompt(e.target.value)} placeholder="Describe the video..." className="min-h-[80px] text-sm" /></div>
				</div>
				<DialogFooter className="border-t pt-4 flex gap-2">
					<Button variant="outline" onClick={onClose}>Cancel</Button>
					<Button className="bg-gradient-to-r from-teal-400 to-cyan-600 text-white gap-1.5"><Sparkles size={14} /> Generate Video</Button>
				</DialogFooter>
			</DialogContent>
		</Dialog>
	);
}

/* ── Shared ──────────────────────────────────────────────────────── */

function Label({ children }: { children: React.ReactNode }) {
	return <label className="text-[10px] font-semibold text-[var(--muted-foreground)] uppercase tracking-wider mb-1.5 block">{children}</label>;
}

function ModelBadge({ label, sub, gradient }: { label: string; sub: string; gradient: string }) {
	return (
		<div className="border border-[var(--border)] rounded-lg px-4 py-3 flex items-center gap-3">
			<div className={`w-8 h-8 rounded-full bg-gradient-to-br ${gradient} flex items-center justify-center text-white text-xs font-bold`}>◆</div>
			<div><p className="text-sm font-medium">{label}</p><p className="text-xs text-[var(--muted-foreground)]">{sub}</p></div>
		</div>
	);
}
